# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"E\n\x15TransformationMessage\x12\x0e\n\x06script\x18\x01 \x01(\t\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error2T\n\x15TransformationService\x12;\n\tTransform\x12\x16.TransformationMessage\x1a\x16.TransformationMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TRANSFORMATIONMESSAGE']._serialized_start=18
  _globals['_TRANSFORMATIONMESSAGE']._serialized_end=87
  _globals['_TRANSFORMATIONSERVICE']._serialized_start=89
  _globals['_TRANSFORMATIONSERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
